### ISSUE TITLE
2003downloads and how we should make it a software, not a subsite.

### ISSUE THREAD

**Issue by PF94** [2003tech/2003page.ga#93]
2003downloads was one of the first subsites to be created, now it was archived, then replanned to be revived, then archived.

You see how ReactOS has RAPPS (**R**eactOS **APP**lication**S** Manager) and how Gnome 2 had "Add/Remove Software"?

Well, i'm trying to do exactly like that, however, there's a problem. There is no Windows version for it, RAPPS doesn't have a setting to use another CAB file (which stores TXT files from another github repo), and i've yet to find something that looks and feels like Gnome 2's "Add/Remove Software", Chocolately does exist, however. It was made for businesses in mind.

So, i've wanted a application that is simillar to RAPPS, but is more "flexible", this means that 2003downloads would need to download a XML file from 2003page, and then list whatever listings that's on the XML file.

Now, i'm sure this will not be made, if it ends up being made, i'm sure it's going to be a lame, god-awful and clunky VB,NET app. meh.

**Comment by EricZhang456** [comment]
Also use OneClick so we can install update of 2003downloads once opening it? *(just like Discord)*

Btw, I think I should take a brake from 2003page now.

**Comment by PF94** [comment]
eh, you should take a break if you want 2003page to fell abandonned and fucking radio slient.

**Comment by PF94** [comment]
anyways my idea is getting nowhere, your "oneclick" idea is passed cause i think it's fucking paid.

**Comment by TALUAtGitHub** [comment]
@PF94: your expectations are too high for what is an open source project. Contributors will leave for whatever reason, and there's nothing you can do about it. These contributors are doing everything for absolutely free in their free time - they should not and will not allow how much they contribute to this project in their limited free time to be dictated in any way, as they will have other things they'd like to do and life to get on with. They'll decide how much to contribute for themselves. If contributors need a break, they WILL get themselves a break no matter what you think is better for yourself and your own project and how much you express that. You really should accept this, because otherwise, there will be a really evident lack of respect between you and contributors, and that makes things MUCH worse as that gives them good reason to abandon the project entirely.

**Comment by PF94** [comment]
I'm going to drop the idea of 2003downloads.

**Comment by PF94** [comment]
Fuck this.
