### ISSUE TITLE
Main Page: WHERE IS CHAZ

### ISSUE THREAD

**Issue by shadowdree** [2003tech/2003page.ga#99]
my name is vriska

i don't have the chazizPF94 button, i use chrome

**Comment by EricZhang456** [comment]
Make sure your screen reader works and read #94

**Comment by PF94** [comment]
Dont read #94, it's out of date.

**Comment by PF94** [comment]
This looks like to be a glitch caused by ethier the CSS, or someone purposefully deleted the jpg.
![Screenshot_20200506-144711_Chrome](https://user-images.githubusercontent.com/45898787/81216244-9d9fe180-8fa8-11ea-96cd-dff1cb34451b.jpg)
However by hovering or clicking on the invisible button, it shows up.

**Comment by PF94** [comment]
I have found the culprit, apparantly it's a oversight by EricAfterEric when he moved most of the buttons to a new folder, he forgot to modify some pieces of code about the "ChazizPF94" button on the buttons.css.
